### Variable réutilisable pour l'URL de base
@baseUrl = http://localhost:3000/api
#* {{baseUrl}} est une variable définie en haut de du fichier .http, permet en cas de changement de port de changer uniquement cette variable 


### GET — Récupérer un objet existant (cas normal, doit réussir)
GET {{baseUrl}}/objet/1

### ==========================================================
### GET — Cas d'erreur : identifiant inexistant
GET {{baseUrl}}/objet/99999

### =========================================================
### PATCH — Modifier le statut d'un objet (cas normal)
PATCH {{baseUrl}}/objet/1/status
Content-Type: application/json

{
  "statut": "en_rayon",
  "prix": 15
}


### PATCH — Cas d'erreur : valeur d'enum invalide
PATCH {{baseUrl}}/objet/1/status
Content-Type: application/json

{
  "statut": "valeur_qui_nexiste_pas"
}