@baseUrl = http://localhost:3000

### GET — Une Statistique, objets par statut, poids total reçu, poids détourné de la déchetterie
GET {{baseUrl}}/statut/1

### GET — Cas d'erreur : id inexistant
GET {{baseUrl}}/depot/99999
