@baseUrl = http://localhost:3000/api

### GET — Une Statistique, objets par statut, poids total reçu, poids détourné de la déchetterie
GET {{baseUrl}}/statuts/1

### GET — Cas d'erreur : id inexistant
GET {{baseUrl}}/statuts/99999
