

services:
  db:
    image: postgres:16
    container_name: adaremise-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: adaremise_user
      POSTGRES_PASSWORD: adaremise_pwd
      POSTGRES_DB: adaremise-db
    ports:
      - "5432:5432"
    volumes:
      - adaremise-db-data:/var/lib/postgresql/data

volumes:
  adaremise-db-data: